apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: daily-rover
    description: A Spring Boot Kotlin service to access the NASA mars rover image API
    tags:
        - kotlin
        - service
        - api
        - spring
    links:
        - url: https://github.com/leeturner/daily-rover-api
          name: GitHub
          icon: github
          type: git
        - url: https://api.nasa.gov
          name: NASA API
          type: api
        - url: https://github.com/chrisccerami/mars-photo-api
          icon: github
          type: git
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: leeturner/daily-rover-api
spec:
    type: service
    system: daily-rover
    lifecycle: production
    owner: team-rover
    apiProvidedBy: daily-rover-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
    name: daily-rover-api
    description: The daily rover API consumed by web components and cli
spec:
    type: openapi
    lifecycle: production
    owner: team-rover