### Get Mars rover details - curiosity
GET https://api.nasa.gov/mars-photos/api/v1/manifests/curiosity?api_key=DEMO_KEY

### Get Mars rover details - spirit
GET https://api.nasa.gov/mars-photos/api/v1/manifests/spirit?api_key=DEMO_KEY

### Get Mars rover details - opportunity
GET https://api.nasa.gov/mars-photos/api/v1/manifests/opportunity?api_key=DEMO_KEY

### Get Mars rover details - perseverance
GET https://api.nasa.gov/mars-photos/api/v1/manifests/perseverance?api_key=DEMO_KEY
